#!/bin/sh
set -eu

# shellcheck disable=SC2034
VERSION=0.1
VINTAGE_PATH=${HOME}/Vintage
DOWNLOAD_PATH=${VINTAGE_PATH}/DOWNLOAD

# shellcheck disable=SC1083
parser_definition() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} [global options...] [command] [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    GLOBAL  -g --global    -- "global flag"
	flag    TASK       --task      -- "global flag"
	flag    SILENT  -s --silent    -- "global flag"
  disp    :usage  -h --help
	disp    VERSION    --version

	msg -- '' 'Commands:'
	cmd add -- "subcommand 1"
	cmd version -- "subcommand 2"
	cmd download -- "subcommand 3"
	cmd extract -- "subcommand 4"
	cmd run -- "subcommand 5"
  cmd exec -- "subcommand 6"
}

# shellcheck disable=SC1083
parser_definition_add() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} add [options...] [archives...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_A  -a --flag-a
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
parser_definition_version() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} version [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_B  -b --flag-b
	param   RESOLVE -r --resolve
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
parser_definition_download() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} download [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_B  -b --flag-b
	param   RESOLVE -r --resolve
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
parser_definition_extract() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} extract [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_B  -b --flag-b
	param   RESOLVE -r --resolve
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
parser_definition_run() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} run [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_B  -b --flag-b
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
parser_definition_exec() {
	setup   REST help:usage abbr:true -- \
		"Usage: ${2##*/} exec [options...] [arguments...]"
	msg -- '' 'getoptions subcommand example' ''
	msg -- 'Options:'
	flag    FLAG_C  -c --flag-c
	disp    :usage  -h --help
}

# shellcheck disable=SC1083
error() {
  echo "$@"
  exit 1
}

eval "$(getoptions parser_definition parse "$0") exit 1"
parse "$@"
eval "set -- $REST"

if [ -z "${SILENT}" ]; then
  if [ -z "${TASK}" ]; then
    echo "Vintage ${VERSION} by Francesco Bianco <bianco@javanile.org>"
  else
    echo "Task: $0 $@"
  fi
fi

if [ $# -gt 0 ]; then
	cmd=$1
	shift
	case $cmd in
		add)
			eval "$(getoptions parser_definition_add parse "$0")"
			parse "$@"
			eval "set -- $REST"
      while [ $# -gt 0 ]; do
        archive=$(echo $1 | cut -d@ -f1)
        version=$(vintage --silent version "${archive}" --resolve "$(echo $1@main | cut -d@ -f2)")
        [ -z "${version}" ] && error "Program or version not found on archive. Missing '$1', visit <https://github.com/francescobianco/vintage> for more details."
        task="vintage --task exec https://github.com/francescobianco/vintage/raw/main/archive/${archive}/${version}/setup.sh"
        ${task}
      	shift
      done
			;;
		version)
			eval "$(getoptions parser_definition_version parse "$0")"
			parse "$@"
			eval "set -- $REST"
			manifest=$(curl -sL "https://raw.githubusercontent.com/francescobianco/vintage/main/archive/$1/MANIFEST.txt")
			[ -z "$RESOLVE" ] && echo "$manifest" || echo "$manifest" | grep "^$RESOLVE" | head -1
			;;
    download)
      eval "$(getoptions parser_definition_download parse "$0")"
      parse "$@"
      eval "set -- $REST"
      #manifest=$(curl -sL "https://raw.githubusercontent.com/francescobianco/vintage/main/archive/$1/MANIFEST.txt")
      #[ -z "$RESOLVE" ] && echo "$manifest" || echo "$manifest" | grep "^$RESOLVE" | head -1
      [ ! -d "${DOWNLOAD_PATH}" ] && mkdir -p "${DOWNLOAD_PATH}"
      download="${DOWNLOAD_PATH}/$1"
      curl -#Lo "${download}" $2
      ls -l "${download}"
      echo "Download complete."
      ;;
    extract)
      eval "$(getoptions parser_definition_extract parse "$0")"
      parse "$@"
      eval "set -- $REST"
      #manifest=$(curl -sL "https://raw.githubusercontent.com/francescobianco/vintage/main/archive/$1/MANIFEST.txt")
      #[ -z "$RESOLVE" ] && echo "$manifest" || echo "$manifest" | grep "^$RESOLVE" | head -1
      echo "EXTRACT"
      ;;
		run)
			eval "$(getoptions parser_definition_run parse "$0")"
			parse "$@"
			eval "set -- $REST"
			#echo "FLAG_B: $FLAG_B"
			;;
		exec)
			eval "$(getoptions parser_definition_exec parse "$0")"
			parse "$@"
			eval "set -- $REST"
			#echo "FLAG_C: $FLAG_C"
      #echo "TASK: $TASK"
			;;
		--) # no subcommand, arguments only
	esac
fi
